# @Author: harshkhajuria
# @Date:   10-Jul-2019 04:09:54 am
# @Email:  khajuriaharsh729@gmail.com
# @Filename: .goreleaser.yml
# @Last modified by:   harshkhajuria
# @Last modified time: 11-Jul-2019 03:33:27 am


# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: horcrux2301
    name: homebrew-tap
  folder: Formula
  description: "Potato is a command line tool which helps you to keep the development configs and settings of your Mac as a programmer safe in your GitHub."
  install: |
    bin.install "Potato"

  test: |
    system "#{bin}/Potato --version"
